# Generated by Django 4.1.7 on 2023-03-23 04:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('traveling', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Detalsity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('date', models.DateField()),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='traveling.city')),
            ],
        ),
    ]
