# Generated by Django 4.1.7 on 2023-03-23 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('traveling', '0001_initial'),
        ('detalsity', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalsity',
            name='image',
            field=models.ImageField(default=1, upload_to='detalsity/image'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='detalsity',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='traveling.city'),
        ),
    ]
